CREATE TABLE IF NOT EXISTS `{prefix}events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `event_type` VARCHAR(100) NULL,
  `excerpt` VARCHAR(500) NULL,
  `content` LONGTEXT NULL,
  `cover_media_id` INT UNSIGNED NULL,
  `gallery_media_ids` VARCHAR(500) NULL,
  `video_url` VARCHAR(255) NULL,
  `external_links` TEXT NULL,
  `drive_url` VARCHAR(255) NULL,
  `attachment_media_ids` VARCHAR(500) NULL,
  `city_id` INT UNSIGNED NULL,
  `venue_name` VARCHAR(191) NULL,
  `maps_url` VARCHAR(255) NULL,
  `starts_at` DATETIME NULL,
  `ends_at` DATETIME NULL,
  `tags` VARCHAR(500) NULL,
  `status` ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_pinned` TINYINT(1) NOT NULL DEFAULT 0,
  `seo_title` VARCHAR(191) NULL,
  `seo_description` VARCHAR(500) NULL,
  `published_at` DATETIME NULL,
  `created_by` INT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `events_slug_unique` (`slug`),
  KEY `events_status_idx` (`status`),
  KEY `events_starts_idx` (`starts_at`),
  KEY `events_city_idx` (`city_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
