CREATE TABLE IF NOT EXISTS `{prefix}gatherings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(500) NULL,
  `cover_media_id` INT UNSIGNED NULL,
  `city_id` INT UNSIGNED NULL,
  `venue` VARCHAR(191) NULL,
  `map_url` VARCHAR(255) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `recurrence_type` ENUM('daily','weekly','monthly','specific_weekdays','custom') NOT NULL DEFAULT 'weekly',
  `recurrence_days` VARCHAR(100) NULL,
  `recurrence_ordinal` TINYINT UNSIGNED NULL,
  `recurrence_custom_text` VARCHAR(255) NULL,
  `recurrence_label` VARCHAR(255) NOT NULL DEFAULT '',
  `starts_on` DATE NOT NULL,
  `ends_on` DATE NULL,
  `status` ENUM('active','paused','ended','pending') NOT NULL DEFAULT 'active',
  `submitted_name` VARCHAR(150) NULL,
  `submitted_phone` VARCHAR(30) NULL,
  `contact_name` VARCHAR(191) NULL,
  `notes` TEXT NULL,
  `created_by` INT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `gatherings_status_idx` (`status`),
  KEY `gatherings_city_idx` (`city_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
